### ISSUE TITLE
Multiple parameters in one secret

### ISSUE THREAD

**Issue by msacchiPPRO** [cmattoon/aws-ssm#9]
If I understand this correctly, currently it's only possible to map 1-1 parameters and secrets key (one SSM parameter per secret).
It would be nice if multiple parameters could be added as multiple key-value pairs in the same secret

**Comment by msacchiPPRO** [comment]
Oh, I just got (by reading the code) the key=value with StringList parameters.
It kind of solves my problem (it's really ugly but it's SSM's fault I guess :)

However, if the StringList is not valid (one entry is not key=value) the program crashes.
I am not a go programmer (or a programmer at all -_-' ) so I cannot propose a fix. 
But it would be nice for the software to manage that exception and keep updating other parameters.

**Comment by tbastos** [comment]
+1

Probably a better solution for multiple parameters in one secret (instead of StringList) would be to specify a SSM "folder" with many parameters, and aws-ssm could get a list of parameters to include in the secret using [SSM.GetParametersByPath](https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#SSM.GetParametersByPath) ?

**Comment by cmattoon** [comment]
Thanks for the report! I've added some more test cases and made the logic a little smarter about parsing the StringList. It's being published as `cmattoon/aws-ssm:PR-10`.

I like the `GetParametersByPath` idea, but I might not get around to it for a little while. My use case is pretty basic and I don't use SSM in conjunction with some of the other config mgmt services/features they offer, so I've been hesitant to make it too fancy. That method does seem like the correct path, though we might have to give some thought as to how merging those params should happen.

**Comment by cmattoon** [comment]
(That fix is available in the `dev` or `latest` image now)

**Comment by cmattoon** [comment]
Closed with v0.1.5
